export const articleData = [
  {
    id: 1,
    heading: "Exploring the Depths of AI",
    subheading: "Unraveling the mysteries behind artificial intelligence",
    tags: ["AI", "Technology", "Innovation"],
    type: "Feature",
    author: "John Doe",
    genre: "Technology",
    date: "2024-02-01",
    picture_url: "https://picsum.photos/800/400/?random",
  },
  {
    id: 2,
    heading: "The Future of Space Travel",
    subheading: "Journeying into the unknown cosmos",
    tags: ["Space", "Science", "Exploration"],
    type: "News",
    author: "Jane Smith",
    genre: "Science",
    date: "2024-02-02",
    picture_url: "https://picsum.photos/800/400/?random",
  },
  {
    id: 3,
    heading: "Eco-Friendly Innovations",
    subheading: "Sustainable technologies shaping the future",
    tags: ["Environment", "Innovation", "Green"],
    type: "Opinion",
    author: "Alan Johnson",
    genre: "Science",
    date: "2024-02-03",
    picture_url: "https://picsum.photos/800/400/?random",
  },
  {
    id: 4,
    heading: "The Art of Culinary Fusion",
    subheading: "Blending flavors from around the world",
    tags: ["Food", "Cuisine", "Travel"],
    type: "Feature",
    author: "Emily Rodriguez",
    genre: "Lifestyle",
    date: "2024-02-04",
    picture_url: "https://picsum.photos/800/400/?random",
  },
  {
    id: 5,
    heading: "The Psychology of Creativity",
    subheading: "Understanding the mind behind innovation",
    tags: ["Psychology", "Creativity", "Mind"],
    type: "Opinion",
    author: "Mark Thompson",
    genre: "Science",
    date: "2024-02-05",
    picture_url: "https://picsum.photos/800/400/?random",
  },
  {
    id: 6,
    heading: "Innovative Fitness Trends",
    subheading: "Breaking the norms in the world of fitness",
    tags: ["Fitness", "Health", "Wellness"],
    type: "News",
    author: "Jessica Miller",
    genre: "Health",
    date: "2024-02-06",
    picture_url: "https://picsum.photos/800/400/?random",
  },
  {
    id: 7,
    heading: "Capturing the Essence of Wildlife",
    subheading: "A photographic journey into the wild",
    tags: ["Wildlife", "Photography", "Nature"],
    type: "Feature",
    author: "David Wilson",
    genre: "Travel",
    date: "2024-02-07",
    picture_url: "https://picsum.photos/800/400/?random",
  },
  {
    id: 8,
    heading: "Revolutionizing Education with Technology",
    subheading: "Tech-driven solutions for a modern learning experience",
    tags: ["Education", "Technology", "Innovation"],
    type: "Opinion",
    author: "Sophie Turner",
    genre: "Technology",
    date: "2024-02-08",
    picture_url: "https://picsum.photos/800/400/?random",
  },
  {
    id: 9,
    heading: "Cultural Heritage Preservation",
    subheading: "The importance of safeguarding our traditions",
    tags: ["Culture", "Heritage", "History"],
    type: "News",
    author: "Carlos Martinez",
    genre: "Culture",
    date: "2024-02-09",
    picture_url: "https://picsum.photos/800/400/?random",
  },
  {
    id: 10,
    heading: "Rising Stars in the Tech Industry",
    subheading: "Spotlight on young talents shaping the future",
    tags: ["Technology", "Innovation", "Career"],
    type: "Feature",
    author: "Olivia Brown",
    genre: "Business",
    date: "2024-02-10",
    picture_url: "https://picsum.photos/800/400/?random",
  },
];
