import { Inter, Urbanist } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

const urbanist = Urbanist({ subsets: ["latin"], variable: "--font-urbanist" });

export const metadata = {
  title: "We Frame",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${urbanist.variable} flex`}>
        <Sidebar />
        <div className=" w-[100%] h-[100vh] min-h-full max-w-full overflow-x-scroll scrollbar-none">
          <Navbar />
          <hr className="shadow" />
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
